server:
  port: 8085
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: categoria-service
              uri: lb://categoria-service
              predicates:
                - Path=/api/categoria/**
            - id: producto-service
              uri: lb://producto-service
              predicates:
                - Path=/api/producto/**
            - id: usuario-service
              uri: lb://usuario-service
              predicates:
                - Path=/api/usuario/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true